### ISSUE TITLE
Error in Matlab wrapper

### ISSUE THREAD

**Issue by ectg** [YutingZhang/fgs-obj#3]
Hi,

I am trying to set up your code on Ubuntu 16.04.1, Matlab R2016a, CPU_ONLY build. Both make and make matcaffe completed successfully, but when I run simple_demo4('000220.jpg'), I get the following error. (**_ldd caffe.mexa64_** indicates that opencv is linked correctly.)  

_Invalid MEX-file '/Projects/fgs-obj-master/caffe/matlab/caffe/caffe.mexa64':
Projects/fgs-obj-master/caffe/matlab/caffe/caffe.mexa64: undefined symbol:
_ZN2**cv6imread**ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEi_

Can you please help?

Thanks!

**Comment by ectg** [comment]
This was due to conflicting opencv versions. Newer versions of Matlab have its own opencv libraries in the bin folder.

**Comment by YutingZhang** [comment]
Thank you for solving the problem by yourself. It is indeed tricky to solve library conflicts with MATLAB. One general solution is to use -L option for mex to specify the external library directory, then mex will first try to first find libraries in the specified folder(s) and then in MATLAB folder. When running the compiled mex file, make sure to also include the external library path in LD_LIBRARY_PATH
